services:
  - type: web
    name: tamilmv-rss-feed
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://<username>:<password>@cluster0.zztswen.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: SCRAPER_URL
        value: https://www.1tamilmv.se/
      - key: REFRESH_INTERVAL
        value: 120
      - key: PORT
        value: 8000
